using System.Security.Claims;
using Identity.Api.Common;
using Identity.Api.Services;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;

namespace Identity.API.UnitTests;

/// <summary>
/// Verifies <see cref="TokenService"/>: refresh-token secrecy/hashing and access-token
/// claim + signature output. 
/// </summary>
public class TokenServiceTests
{
    private static TokenService CreateService()
    {
        // Arrange: in-memory config, real RSA key generated by the service.
        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["Jwt:Issuer"] = "test-issuer",
                ["Jwt:Audience"] = "test-audience",
                ["Jwt:AccessTtlSeconds"] = "60",
                ["Jwt:RefreshTtlSeconds"] = "120",
            })
            .Build();
        return new TokenService(config);
    }

    [Fact]
    public void CreateRefreshToken_Returns_Opaque_Token_Different_From_Hash()
    {
        // Arrange
        // Act
        var (raw, hash) = TokenService.CreateRefreshToken();

        // Assert
        Assert.False(string.IsNullOrEmpty(raw));
        Assert.False(string.IsNullOrEmpty(hash));
        Assert.NotEqual(raw, hash);
    }

    [Fact]
    public void CreateRefreshToken_Generates_Unique_Tokens_Each_Call()
    {
        // Arrange
        // Act
        var (raw1, _) = TokenService.CreateRefreshToken();
        var (raw2, _) = TokenService.CreateRefreshToken();

        // Assert
        Assert.NotEqual(raw1, raw2);
    }

    [Fact]
    public void HashRefreshToken_Is_Stable_And_Lossy()
    {
        // Arrange
        var (raw, hash) = TokenService.CreateRefreshToken();

        // Act
        var rehashed = TokenService.HashRefreshToken(raw);

        // Assert
        Assert.Equal(hash, rehashed);
        Assert.Equal(44, hash.Length); // SHA-256 → 32 bytes → base64 == 44 chars
    }

    [Fact]
    public void CreateAccessToken_Carries_Standard_Claims()
    {
        // Arrange
        var svc = CreateService();
        var tenantId = Guid.NewGuid();
        var user = new ApplicationUser
        {
            Id = Guid.NewGuid(),
            Email = "alice@example.com",
            TenantId = tenantId,
        };
        var now = new DateTimeOffset(2025, 1, 1, 0, 0, 0, TimeSpan.Zero);

        // Act
        var token = svc.CreateAccessToken(user, new[] { "Admin" }, now);
        var decoded = new JsonWebTokenHandler().ReadJsonWebToken(token);

        // Assert
        Assert.Equal(user.Id.ToString(), decoded.GetClaim(JwtRegisteredClaimNames.Sub)?.Value);
        Assert.Equal(user.Email, decoded.GetClaim(JwtRegisteredClaimNames.Email)?.Value);
        Assert.Equal(tenantId.ToString(), decoded.GetClaim("tid")?.Value);
        Assert.Equal(svc.Issuer, decoded.GetClaim(JwtRegisteredClaimNames.Iss)?.Value);
        Assert.Contains(decoded.Claims, c => c.Type == ClaimTypes.Role && c.Value == "Admin");
    }

    [Fact]
    public void CreateAccessToken_Deduplicates_Roles()
    {
        // Arrange
        var svc = CreateService();
        var user = new ApplicationUser { Id = Guid.NewGuid(), TenantId = Guid.NewGuid() };

        // Act
        var token = svc.CreateAccessToken(user, new[] { "admin", "admin", "manager" }, DateTimeOffset.UtcNow);
        var decoded = new JsonWebTokenHandler().ReadJsonWebToken(token);

        // Assert
        // Distinct() is case-sensitive, so exact "admin" appears once; 2 distinct roles total.
        var roles = decoded.Claims.Where(c => c.Type == ClaimTypes.Role)
            .Select(c => c.Value).ToArray();
        Assert.Equal(2, roles.Length);
    }

    [Fact]
    public void AccessToken_Expires_Per_Configured_Ttl()
    {
        // Arrange
        var svc = CreateService();
        var user = new ApplicationUser { Id = Guid.NewGuid(), TenantId = Guid.NewGuid() };
        var now = new DateTimeOffset(2025, 1, 1, 0, 0, 0, TimeSpan.Zero);

        // Act
        var token = svc.CreateAccessToken(user, Array.Empty<string>(), now);
        var decoded = new JsonWebTokenHandler().ReadJsonWebToken(token);

        // Assert
        Assert.Equal(now.AddSeconds(svc.AccessTtlSeconds), decoded.ValidTo);
    }

    [Fact]
    public async Task AccessToken_Verifies_With_The_Services_Signing_Key()
    {
        // Arrange
        var svc = CreateService();
        var user = new ApplicationUser { Id = Guid.NewGuid(), TenantId = Guid.NewGuid() };
        var token = svc.CreateAccessToken(user, Array.Empty<string>(), DateTimeOffset.UtcNow);
        var handler = new JsonWebTokenHandler();

        // Act
        var result = await handler.ValidateTokenAsync(token, new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = svc.Issuer,
            ValidAudience = svc.Audience,
            IssuerSigningKey = svc.SigningKey,
        });

        // Assert
        Assert.True(result.IsValid);
    }
}